let data = [
  {
    maPhim: 1435,
    tenPhim: "Mad Max: Fury Road 2",
    biDanh: "mad-max-fury-road-2",
    trailer: "https://www.youtube.com/embed/hEJnMQG9ev8",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/madmax.jpg",
    moTa: "In a stark desert landscape where humanity is broken, two rebels just might be able to restore order: Max, a man of action and of few words, and Furiosa, a woman of action who is looking to make it back to her childhood homeland.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-04T10:33:02.673",
    danhGia: 7,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 1450,
    tenPhim: "True Detective! 6788",
    biDanh: "true-detective-6788",
    trailer: "https://www.youtube.com/embed/MKioqc2uT0I",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/truedetective.jpg",
    moTa: "An anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law. law",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-06-05T21:55:27.573",
    danhGia: 5,
    hot: true,
    dangChieu: true,
    sapChieu: true,
  },
  {
    maPhim: 1465,
    tenPhim: "The Longest Ride 123",
    biDanh: "the-longest-ride-123",
    trailer: "https://www.youtube.com/embed/FUS_Q7FsfqU",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/thelongestride.jpg",
    moTa: "After an automobile crash, the lives of a young couple intertwine with a much older man, as he reflects back on a past love.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-03T19:57:43.443",
    danhGia: 7,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 1480,
    tenPhim: "The Walking Dead 7",
    biDanh: "the-walking-dead-7",
    trailer: "https://www.youtube.com/embed/R1v0uFms68U",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/thewalkingdead.jpg",
    moTa: "Sheriff's Deputy Rick Grimes leads a group of survivors in a world overrun by zombies.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-03T18:56:27.63",
    danhGia: 5,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 1495,
    tenPhim: "Southpaw 123",
    biDanh: "southpaw-123",
    trailer: "https://www.youtube.com/embed/Mh2ebPxhoLs",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/southpaw.jpg",
    moTa: "Boxer Billy Hope turns to trainer Tick Willis to help him get his life back on track after losing his wife in a tragic accident and his daughter to child protection services.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-07T14:05:04.157",
    danhGia: 5,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 1510,
    tenPhim: "Specter 789",
    biDanh: "specter-789",
    trailer: "https://www.youtube.com/embed/LTDaET-JweU",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/spectre.jpg",
    moTa: "A cryptic message from Bond's past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-06T13:03:14.057",
    danhGia: 5,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 1525,
    tenPhim: "Avengers: Cuộc Chiến Vô Cực1",
    biDanh: "avengers-cuoc-chien-vo-cuc1",
    trailer: "https://www.youtube.com/embed/DKqu9qc-5f4",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/avengers-cuoc-chien-vo-cuc1_gp02.jpg",
    moTa: "Sau chuyến hành trình độc nhất vô nhị không ngừng mở rộng và phát triển vụ trũ điện ảnh Marvel, bộ phim Avengers: Cuộc Chiến Vô Cực sẽ mang đến màn ảnh trận chiến cuối cùng khốc liệt nhất mọi thời đại. Biệt đội Avengers và các đồng minh siêu anh hùng của họ phải chấp nhận hy sinh tất cả để có thể chống lại kẻ thù hùng mạnh Thanos trước tham vọng hủy diệt toàn bộ vũ trụ của hắn",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-01-25T00:00:00",
    danhGia: 10,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 1540,
    tenPhim: "TAY XẠ THỦ 123",
    biDanh: "tay-xa-thu-123",
    trailer: "https://www.youtube.com/embed/wiFXHfW-ddA",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/tay-xa-thu_gp02.jpg",
    moTa: 'Jim - một cựu thủy quân lục chiến tại biên giới bang Arizona vô tình bị cuốn theo cuộc truy lùng của băng Vasquez khi cố giúp đưa Miguel thoát khỏi chúng. Nhiệm vụ giờ đây của Jim là "vận chuyển" Miguel về Chicago cùng gia đình trước sự truy giết máu lạnh của băng đảng Vasquez.',
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-03T18:51:33.913",
    danhGia: 10,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 4125,
    tenPhim: "Ròm 384",
    biDanh: "rom-384",
    trailer: "https://www.youtube.com/embed/XRm1P7oGpMQ",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/rom_gp02.jpg",
    moTa: "Lấy bối cảnh từ một khu chung cư cũ đang chờ giải tỏa tại Sài Gòn, Ròm kể câu chuyện về cuộc sống của những người dân lao động nơi đây. Họ đều chơi số đề với hy vọng kiếm được một khoản tiền lớn để đổi đời. Ròm là cậu bé làm “cò đề” để kiếm sống qua ngày, chuyên tư vấn cho người dân những con số may mắn để họ có cơ may trúng đề. Một hôm cậu giúp bà già kia trúng đề lớn nên được mọi người tin tưởng nhưng sau nhiều lần thua cậu bị người dân mất tin tưởng, kết phim thì mở bài hát chạy của wowwy ",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-14T23:08:22.837",
    danhGia: 10,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 6078,
    tenPhim: "death Stranding",
    biDanh: "death-stranding",
    trailer: "https://www.youtube.com/embed/tCI396HyhbQ",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/death-stranding_gp02.jpg",
    moTa: "From legendary game creator Hideo Kojima comes an all-new, genre-defying experience. Sam Bridges must brave a world utterly transformed by the Death Stranding. Carrying the disconnected remnants of our future in his hands, he embarks on a journey to reconnect the shattered world one step at a time.",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-04-02T00:00:00",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 6079,
    tenPhim: "Bố Già",
    biDanh: "bo-gia",
    trailer: "https://www.youtube.com/embed/jluSu8Rw6YE",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/le-anh-quang_gp02.jpeg",
    moTa: "Bố già là một bộ phim điện ảnh hài tình cảm của Việt Nam do Trấn Thành Town, HKFilm và Galaxy Studio sản xuất, dựa trên bộ phim chiếu mạng cùng tên của Trấn Thành được phát hành vào dịp Tết Nguyên Đán 2020",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-10-02T00:00:00",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 6315,
    tenPhim: "Thiên thần hộ mệnh",
    biDanh: "thien-than-ho-menh",
    trailer: "https://www.youtube.com/embed/FzoWWAJeFgM",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/thien-than-ho-menh_gp02.jpg",
    moTa: "Cái chết bí ẩn của một ngôi sao trong giới giải trí, được đồn đoán rằng có liên quan đến loại búp bê ma thuật có tính chất bùa ngải hắc ám. Liệu bí ẩn khủng khiếp nào đang bị che giấu?",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-06-24T00:00:00",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 6380,
    tenPhim: "Coffee barista",
    biDanh: "coffee-barista",
    trailer: "https://youtube.com/embed/JGP-Cvl_0Tk",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/coffee-barista_gp02.jpg",
    moTa: "A coffee make a person awakes.",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-07-06T02:36:59.213",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 6381,
    tenPhim: "Cô gái đến từ hư vô",
    biDanh: "co-gai-den-tu-hu-vo",
    trailer: "https://www.youtube.com/embed/YF2NfHkn0vM",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/co-gai-den-tu-hu-vo_gp02.jpg",
    moTa: "Girl from Nowhere là series phim giật gân của Thái Lan, ra mắt năm 2018. Tác phẩm gồm nhiều câu chuyện ngắn, xoay quanh những góc tối học đường như nạn quay cóp, bắt nạt, tham nhũng, bệnh thành tích, tình dục tuổi vị thành niên… Tại Việt Nam, phim còn được biết đến với tên gọi Cô gái đến từ hư vô.",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-06-03T00:00:00",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 6735,
    tenPhim: "Trạng Tí Phiêu Lưu Ký",
    biDanh: "trang-ti-phieu-luu-ky",
    trailer: "https://www.youtube.com/embed/l2XBzUZidig",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/trang-ti-phieu-luu-ky_gp02.jpg",
    moTa: "Trạng Tí chuyển thể từ truyện tranh nổi tiếng Thần đồng đất Việt, xoay quanh Tí - cậu bé thông minh, láu lỉnh. Cùng các bạn Sửu, Dần, Mẹo, cậu nhiều lần giúp triều đình thoát khỏi các tình huống nguy hiểm, chống lại ngoại bang.",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-04-30T00:00:00",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 6736,
    tenPhim:
      "Detective Conan: Scarlet Bullet - Thám Tử Lừng Danh Conan: Viên Đạn Đỏ",
    biDanh:
      "detective-conan-scarlet-bullet-tham-tu-lung-danh-conan-vien-dan-do",
    trailer: "https://www.youtube.com/embed/lOq4F7tLpxU",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/detective-conan-scarlet-bullet-tham-tu-lung-danh-conan-vien-dan-do_gp02.jpg",
    moTa: 'Nhật Bản đang tổ chức lễ kỷ niệm World Sports Games (WSG), sự kiện thể thao lớn nhất thế giới tại Tokyo. "Shinkansen", con tàu siêu dẫn ống chân không đầu tiên trên thế giới được chế tạo từ công nghệ mới nhất của Nhật Bản sẽ được mở chạy và có thời gian trùng với thời khắc khai mạc WSG. Con tàu được thiết lập chạy từ Ga Shin Nagoya đến Ga Tokyo với tốc độ 1000km/h. Tuy nhiên, một sự cố kỳ lạ đã diễn ra trong bữa tiệc của các nhà tài trợ nổi tiếng, theo sau đó chính là hàng loạt vụ bắt cóc các giám đốc điều hành. Conan đã liên kết vụ này về vụ án bắt cóc hàng loạt liên quan đến WSG vào 15 năm trước ở Boston.',
    maNhom: "GP02",
    ngayKhoiChieu: "2021-06-17T10:24:22.663",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 7018,
    tenPhim: "Hùng Thần Trắng - Great White",
    biDanh: "hung-than-trang-great-white",
    trailer: "https://www.youtube.com/embed/A7eqA3Z96kk",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/hung-than-trang-great-white_gp02.jpg",
    moTa: "Hung Thần Trắng là bộ phim kể về vụ truy sát kinh hoàng bởi loài cá mập trắng khổng lồ diễn ra tại Hell’s Reef, cách xa bờ 200 dặm đã khiến nhiều người thiệt mạng. Một nhóm người đang đi nghỉ mát. Kỳ nghỉ trong mơ bỗng biến thành thảm kịch khi cả 5 người phải giành giật sự sống chỉ với một chiếc phao cứu hộ giữa biển cả mênh mông và kẻ săn mồi trực diện chính là hung thần khát máu thống trị đại dương.\n",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-07-05T00:00:00",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 7102,
    tenPhim: "End Game 1",
    biDanh: "end-game-1",
    trailer: 'https://www.youtube.com/embed/TcMBFSGVi1c"',
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/end-game-1_gp02.jpg",
    moTa: "End Game Avenger",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-07-06T02:36:04.077",
    danhGia: 10,
    hot: null,
    dangChieu: null,
    sapChieu: null,
  },
  {
    maPhim: 8478,
    tenPhim: "High Class: Đẳng Cấp Thượng Lưu",
    biDanh: "high-class-dang-cap-thuong-luu",
    trailer: "https://www.youtube.com/embed/QbBiH_mfX0U",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/high-class-dang-cap-thuong-luu_gp02.jpg",
    moTa: "High Class là bộ phim truyền hình bí ẩn, hồi hộp kể về Song Yeo Wool - cựu luật sư mất tất cả vì bị buộc tội sát hại chồng mình. Từ đây, các bí mật bẩn thỉu, sự dối trá và thói đạo đức giả đằng sau cuộc sống hoàn hảo của những người phụ nữ ưu tú trong xã hội Hàn Quốc dần được hé lộ.",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-02-10T00:00:00",
    danhGia: 9,
    hot: false,
    dangChieu: true,
    sapChieu: true,
  },
  {
    maPhim: 8803,
    tenPhim: "Fantastic Beasts 2",
    biDanh: "fantastic-beasts-2",
    trailer: "https://youtu.be/8bYBOVWLNIs",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/fantastic-beasts-2_gp02.jpg",
    moTa: "Một vài tháng khi Newt Scamander (Eddie Redmayne) giúp vén màn bí mật và bắt giữ phù thủy bóng tối Gellert Grindelwald (Johnny Depp). Tuy nhiên, Grinderwald đã làm một cuộc tẩu thoát ngoạn mục và thu nạp được lực lượng những người đi theo mình. Người duy nhất trong hoàn cảnh bấy giờ có thể ngăn chặn Grindelwald chính là Albus Dumbledore (Jude Law). Cuộc hành trình chống lại thế lực bóng tối này còn có sự góp mặt của Tina (Katherine Waterson), Queenie (Alison Sudol) và Jacob (Dan Fogler). Đây sẽ là phép thử để mọi người chứng minh lòng trung thành khi đối mặt với thế lực bóng đêm. ",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-01-31T00:00:00",
    danhGia: 8,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8810,
    tenPhim: "Fantastic Beasts 3",
    biDanh: "fantastic-beasts-3",
    trailer: "https://youtu.be/DaM_wL1ZOM4",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/fantastic-beasts-3_gp02.jpg",
    moTa: "Fantastic Beasts 3 is almost with us and we now have a brand-new trailer to tide us over until it arrives in April.  The delayed threequel, aka Fantastic Beasts: The Secrets of Dumbledore, has had its fair share of delays behind the scenes, as well as major casting changes as Mads Mikkelsen has taken over from Johnny Depp as Grindelwald.  After all that though, it seems as though things are on track for the new movie to arrive in cinemas very soon. The previous two movies were of mixed quality, but it's still a chance to revisit the magical universe of Harry Potter – and who can resist that?",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-04-05T00:00:00",
    danhGia: 8,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8812,
    tenPhim: "Thám Tử Lừng Danh Conan Movie 24: Viên đạn đỏ",
    biDanh: "tham-tu-lung-danh-conan-movie-24-vien-dan-do",
    trailer: "https://youtu.be/-jV9aLm_xCo",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/tham-tu-lung-danh-conan-movie-24-vien-dan-do_gp02.jpg",
    moTa: 'Nhật Bản đang chuẩn bị chào đón buổi lễ đăng cai ở Tokyo để kỷ niệm "WSG: World Sports Games", đại hội thể thao lớn nhất hành tinh. Bên cạnh buổi lễ khai mạc, "Tuyến tính siêu dẫn chân không (Tàu siêu tốc chuyển động trên đệm từ trường)" đầu tiên trên thế giới khiến nước Nhật tự hào với tốc độ tối đa 1000km/h và đã tập hợp tất cả các công nghệ tốt nhất của Nhật cũng được phát biểu. Nó sẽ được phát triển giữa ga Shibahama mới được thành lập ở Tokyo và ga Shin-Nagoya. Trong khi đang thu hút sự chú ý của mọi người trên thế giới, đột nhiên sự cố xảy ra ở một địa điểm tổ chức tiệc, nơi các nhà tài trợ đại hội nổi tiếng tụ tập. Một tình huống bất thường xảy khi người của các doanh nghiệp đứng đầu liên tiếp bị bắt cóc. Đằng sau đó là bóng dáng của Shuuichi Akai đang theo dõi vụ việc và có cả bóng dáng của FBI đang chờ lệnh từ Akai. Theo như suy luận của Conan, cho thấy vụ án này có mối liên hệ với vụ bắt cóc liên tiếp WSG tồi tệ đã xảy ra ở Boston, Hoa Kỳ vào 15 năm trước và lúc bấy giờ vụ án này cũng thuộc thẩm quyền của FBI. Có thật sự cố này chỉ là ngẫu nhiên? Rất nhiều người trên thế giới đang tập trung tại Nhật Bản! Liệu có chuyện gì sắp xảy ra!? Khi "Viên đạn Nhật Bản", tuyến tính siêu dẫn chân không khởi động. "Cả gia đình" nguy hiểm tập hợp . Bây giờ sự cộng hưởng bắt đầu!',
    maNhom: "GP02",
    ngayKhoiChieu: "2022-03-21T15:08:51.53",
    danhGia: 11,
    hot: false,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8823,
    tenPhim: "Loki 2022",
    biDanh: "loki-2022",
    trailer: "https://youtu.be/dE1P4zDhhqw",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/loki-2022_gp02.png",
    moTa: "Tony Stark Dead",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-03-21T19:39:09.563",
    danhGia: 3,
    hot: false,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8876,
    tenPhim: "Arcane",
    biDanh: "arcane",
    trailer: "https://youtu.be/4Ps6nV4wiCE",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/arcane_gp02.jpg",
    moTa: "Phim của Riot về Liên Mình Huyền Thoại",
    maNhom: "GP02",
    ngayKhoiChieu: "2021-11-20T00:00:00",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 8889,
    tenPhim: "Ma tốc độ",
    biDanh: "ma-toc-do",
    trailer: "https://www.youtube.com/watch?v=Nuemk7Y7cjM",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/ma-toc-do_gp02.jpg",
    moTa: "Phim hành động Mỹ, đua xe bắn súng",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-20T00:00:00",
    danhGia: 8,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8905,
    tenPhim: "Dune - Hành tinh cát",
    biDanh: "dune-hanh-tinh-cat",
    trailer: "https://www.youtube.com/watch?v=n9xhJrPXop4",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/dune-hanh-tinh-cat_gp02.jpg",
    moTa: "Phim điện ảnh Mỹ, hành động, viễn tưởng",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-21T00:00:00",
    danhGia: 9,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 8907,
    tenPhim: "Doctor Strange 2",
    biDanh: "doctor-strange-2",
    trailer: "https://www.youtube.com/watch?v=aWzlQ2N6qqg",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/doctor-strange-2_gp02.jpg",
    moTa: "Phim điện ảnh Marvel, Phù thủy tối thượng, đa vũ trụ",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-07T14:29:26.38",
    danhGia: 10,
    hot: true,
    dangChieu: false,
    sapChieu: true,
  },
  {
    maPhim: 9022,
    tenPhim: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc Trailer",
    biDanh: "demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-trailer",
    trailer: "https://www.youtube.com/embed/UN66i-JWaWc",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-trailer_gp02.jpg",
    moTa: "Hi, Nezuko so cute",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-24T19:59:38.29",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 9023,
    tenPhim: "Doctor Strange",
    biDanh: "doctor-strange",
    trailer: "https://youtu.be/3xccmeAsy8g",
    hinhAnh:
      "https://movienew.cybersoft.edu.vn/hinhanh/doctor-strange_gp02.png",
    moTa: "Sau các sự kiện của Avengers: Endgame, Tiến sĩ Stephen Strange tiếp tục nghiên cứu về Viên đá Thời gian. Nhưng một người bạn cũ đã trở thành kẻ thù tìm cách tiêu diệt mọi phù thủy trên Trái đất, làm xáo trộn kế hoạch của Strange và cũng khiến anh ta mở ra một tội ác khôn lường.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-05-24T00:00:00",
    danhGia: 10,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
  {
    maPhim: 9127,
    tenPhim: "The Boys",
    biDanh: "the-boys",
    trailer:
      "https://www.youtube.com/watch?v=elTgqUW-NYE&ab_channel=PrimeVideo",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/the-boys_gp02.jpeg",
    moTa: "Tưởng như thế giới đã bão hòa với dòng phim siêu anh hùng, sau thành công của Marvel và DC với sự bành trướng từ vũ trụ điện ảnh và tỉ lệ “đẻ trứng” sòn sòn dăm ba bữa lại một bom tấn siêu anh hùng ra đời. Thế nhưng Amazon đã chứng minh rằng không gì là không thể, ngay cả việc cười vào mũi Superman. Đến từ nhà sản xuất Seth Rogen và Eric Kripke từng rất thành công với Preacher, series The Boys (tạm dịch: Anh Hùng Phá Hoại) biến siêu anh hùng thành phản diện và cợt nhả với điều đó.",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-06-14T00:00:00",
    danhGia: 5,
    hot: true,
    dangChieu: true,
    sapChieu: true,
  },
  {
    maPhim: 9177,
    tenPhim: "aaa",
    biDanh: "aaa",
    trailer: "sss",
    hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/aaa_gp02.png",
    moTa: "ssss",
    maNhom: "GP02",
    ngayKhoiChieu: "2022-06-14T00:00:00",
    danhGia: 3,
    hot: true,
    dangChieu: true,
    sapChieu: false,
  },
];
