let data = {
  data: {
    statusCode: 200,
    message: "Xử lý thành công!",
    content: [
      {
        maPhim: 1347,
        tenPhim: "Inside Out phần 4",
        biDanh: "inside-out-phan-4",
        trailer: "https://www.youtube.com/embed/seMwpP0yeu4",
        hinhAnh:
          "https://movienew.cybersoft.edu.vn/hinhanh/inside-out-2s59_gp04.jpg",
        moTa: "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
        maNhom: "GP04",
        ngayKhoiChieu: "2022-06-13T22:32:38.5",
        danhGia: 12,
        hot: true,
        dangChieu: false,
        sapChieu: false,
      },
      {
        maPhim: 1377,
        tenPhim: "Batman v Superman: Dawn of Justice",
        biDanh: "batman-v-superman-dawn-of-justice",
        trailer: "https://www.youtube.com/embed/0WWzgGyAH6Y",
        hinhAnh:
          "https://movienew.cybersoft.edu.vn/hinhanh/batmanvssuperman.jpg",
        moTa: "Fearing the actions of a god-like Super Hero left unchecked, Gotham City's own formidable, forceful vigilante takes on Metropolis most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it's ever known before.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: false,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 1392,
        tenPhim: "Ant-Man",
        biDanh: "ant-man",
        trailer: "https://www.youtube.com/embed/1HpZevFifuo",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/antman.jpg",
        moTa: "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 1407,
        tenPhim: "Jurassic World",
        biDanh: "jurassic-world",
        trailer: "https://www.youtube.com/embed/RFinNxS5KN4",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/jurassicworld.jpg",
        moTa: "A new theme park is built on the original site of Jurassic Park. Everything is going well until the park's newest attraction--a genetically modified giant stealth killing machine--escapes containment and goes on a killing spree.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: false,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 1422,
        tenPhim: "Fantastic Four",
        biDanh: "fantastic-four",
        trailer: "https://www.youtube.com/embed/AAgnQdiZFsQ",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/fantasticfour.jpg",
        moTa: "Four young outsiders teleport to an alternate and dangerous universe which alters their physical form in shocking ways. The four must learn to harness their new abilities and work together to save Earth from a former friend turned enemy.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 1437,
        tenPhim: "Mad Max: Fury Road",
        biDanh: "mad-max-fury-road",
        trailer: "https://www.youtube.com/embed/hEJnMQG9ev8",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/madmax.jpg",
        moTa: "In a stark desert landscape where humanity is broken, two rebels just might be able to restore order: Max, a man of action and of few words, and Furiosa, a woman of action who is looking to make it back to her childhood homeland.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: false,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 1452,
        tenPhim: "True Detective",
        biDanh: "true-detective",
        trailer: "https://www.youtube.com/embed/TXwCoNwBSkQ",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/truedetective.jpg",
        moTa: "An anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 1467,
        tenPhim: "The Longest Ride",
        biDanh: "the-longest-ride",
        trailer: "https://www.youtube.com/embed/FUS_Q7FsfqU",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/thelongestride.jpg",
        moTa: "After an automobile crash, the lives of a young couple intertwine with a much older man, as he reflects back on a past love.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: false,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 1482,
        tenPhim: "The Walking Dead",
        biDanh: "the-walking-dead",
        trailer: "https://www.youtube.com/embed/R1v0uFms68U",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/thewalkingdead.jpg",
        moTa: "Sheriff's Deputy Rick Grimes leads a group of survivors in a world overrun by zombies.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 1497,
        tenPhim: "Southpaw",
        biDanh: "southpaw",
        trailer: "https://www.youtube.com/embed/Mh2ebPxhoLs",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/southpaw.jpg",
        moTa: "Boxer Billy Hope turns to trainer Tick Willis to help him get his life back on track after losing his wife in a tragic accident and his daughter to child protection services.",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: false,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 1512,
        tenPhim: "Specter",
        biDanh: "specter",
        trailer: "https://www.youtube.com/embed/LTDaET-JweU",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/spectre.jpg",
        moTa: "A cryptic message from Bond's past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
        maNhom: "GP04",
        ngayKhoiChieu: "2020-10-10T00:00:00",
        danhGia: 10,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 1527,
        tenPhim: "Avengers: Infinity War ",
        biDanh: "avengers-infinity-war",
        trailer: "https://www.youtube.com/embed/DKqu9qc-5f4",
        hinhAnh:
          "https://movienew.cybersoft.edu.vn/hinhanh/avengers-infinity-war.jpg",
        moTa: "Biệt đội siêu anh hùng Avengers và những đồng minh sẽ phải sẵn sàng hi sinh tính mạng để chống lại siêu ác nhân hùng mạnh Thanos trước khi hắn phá huỷ mọi thứ và đặt dấu chấm hết cho vũ trụ. ",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: false,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 1542,
        tenPhim: "Avengers: Infinity War ",
        biDanh: "avengers-infinity-war",
        trailer: "https://www.youtube.com/embed/DKqu9qc-5f4",
        hinhAnh:
          "https://movienew.cybersoft.edu.vn/hinhanh/avengers-infinity-war.jpg",
        moTa: "Biệt đội siêu anh hùng Avengers và những đồng minh sẽ phải sẵn sàng hi sinh tính mạng để chống lại siêu ác nhân hùng mạnh Thanos trước khi hắn phá huỷ mọi thứ và đặt dấu chấm hết cho vũ trụ. ",
        maNhom: "GP04",
        ngayKhoiChieu: "2019-07-29T00:00:00",
        danhGia: 5,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 8513,
        tenPhim: "Minion",
        biDanh: "minion",
        trailer: "",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/minion_gp04.jpg",
        moTa: "",
        maNhom: "GP04",
        ngayKhoiChieu: "2020-10-10T00:00:00",
        danhGia: 0,
        hot: false,
        dangChieu: false,
        sapChieu: false,
      },
      {
        maPhim: 8589,
        tenPhim: "Phim Spider Man: No Way Home",
        biDanh: "phim-spider-man-no-way-home",
        trailer: "https://youtu.be/MR0TlzRAXHY",
        hinhAnh:
          "https://movienew.cybersoft.edu.vn/hinhanh/phim-spider-man-no-way-home_gp04.jfif",
        moTa: "Phim Người Nhện - Không Còn Nhà 2021 Full HD Vietsub | Spider-Man: No Way Home 2021 Phim Spider-Man: No Way Home 2021 trông giống như bộ phim Marvel lớn",
        maNhom: "GP04",
        ngayKhoiChieu: "2021-12-22T00:00:00",
        danhGia: 6,
        hot: true,
        dangChieu: false,
        sapChieu: true,
      },
      {
        maPhim: 8795,
        tenPhim: "deadpool",
        biDanh: "deadpool",
        trailer: "https://www.youtube.com/embed/XaX-d0avSz4",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/deadpool_gp04.jpeg",
        moTa: "hâhádasdassaad",
        maNhom: "GP04",
        ngayKhoiChieu: "2022-02-17T00:00:00",
        danhGia: 5,
        hot: true,
        dangChieu: true,
        sapChieu: false,
      },
      {
        maPhim: 8796,
        tenPhim: "da223232",
        biDanh: "da223232",
        trailer: "https://www.youtube.com/embed/XaX-d0avSz4",
        hinhAnh: "https://movienew.cybersoft.edu.vn/hinhanh/da223232_gp04.jpeg",
        moTa: "adasasdsdasdasdasd",
        maNhom: "GP04",
        ngayKhoiChieu: "2022-02-02T00:00:00",
        danhGia: 0,
        hot: true,
        dangChieu: true,
        sapChieu: true,
      },
      {
        maPhim: 8851,
        tenPhim: "Công tố viên chuyển sinh",
        biDanh: "cong-to-vien-chuyen-sinh",
        trailer: "youtube.com/watch?v=H8qti-dUUmU",
        hinhAnh:
          "https://movienew.cybersoft.edu.vn/hinhanh/cong-to-vien-chuyen-sinh_gp04.jpg",
        moTa: "Công tố viên chuyển sinh",
        maNhom: "GP04",
        ngayKhoiChieu: "2020-10-10T00:00:00",
        danhGia: 9,
        hot: true,
        dangChieu: true,
        sapChieu: false,
      },
    ],
    dateTime: "2022-06-26T22:42:51.4722072+07:00",
    messageConstants: null,
  },
  status: 200,
  statusText: "OK",
  headers: {
    "content-type": "application/json; charset=utf-8",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: null,
    },
    headers: {
      Accept: "application/json, text/plain, */*",
      TokenCybersoft:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCBTw6FuZyAwMyIsIkhldEhhblN0cmluZyI6IjAxLzAxLzIwMjMiLCJIZXRIYW5UaW1lIjoiMTY3MjUzMTIwMDAwMCIsIm5iZiI6MTY0NzUzNjQwMCwiZXhwIjoxNjcyNjc4ODAwfQ.v1pky9yKwnujpoxePbaS26rxq_cGpKrk0GvA0sHAVqY",
    },
    method: "get",
    url: "https://movienew.cybersoft.edu.vn/api/QuanLyPhim/LayDanhSachPhim?maNhom=GP04",
  },
  request: {},
};
